import type {
  Content,
  StyleDictionary,
  TDocumentDefinitions,
} from 'pdfmake/interfaces';
import { Formatter } from './formatter';

const top: Content = {
  image: 'src/assets/top.png',
  // width: ,
  absolutePosition: {
    x: 0,
    y: 0,
  },
};

const logo: Content = {
  image: 'src/assets/logo.png',
  width: 69,
  marginTop: -15,
  alignment: 'left',
};

const icons: { [key: string]: Content } = {
  result: {
    image: 'src/assets/icons/result.png',
    width: 12,
  },
  time: {
    image: 'src/assets/icons/time.png',
    width: 12,
  },
};

// const location = 'Улаанбаатар хот, ХанУул дүүрэг, 11-р хороо, Жардин хотхон';
// const town = 'Jardin хотхон';
// const type = 'Орон сууц';
// const value = {
//   min: 1200000,
//   max: 2500000,
//   avg: 1950000,
//   area: 80,
// };
const oronSuutsniiUniinOsolt = 12;
const hunAminOsoltHugjil = 3;
const heregleeniiUniinIndex = 8;
// const user = {
//   name: 'Алтангэрэл ЭРДЭМСАЙХАН',
//   email: 'erdemsaikhan.dev@gmail.com',
//   phone: '+976-8899-2864',
// };

// const text =
//   'Таны Улаанбаатар хот, Хан уул дүүрэг, 11-р хороо, 17020, Жардин хотхон, 120-р байр, 6 дугаар давхарын 3 өрөө 80м.кв орон сууцны өнөөгийн зах зээлийн үнэ 160,950,000.00 төгрөг орчмын үнэтэй байна.';

const styles: StyleDictionary = {
  h1: {
    fontSize: 20,
    
    bold: true,
    margin: [0, 5],
  },
  h2: {
    fontSize: 16,
    bold: true,
  },
  h3: {
    fontSize: 12,
    color: '#1D1E44',
  },
  h4: {
    fontSize: 10,
    color: '#1D1E44',
  },
};

export const RequestReport = ({
  text,
  user,
  value,
  town,
  type,
  location,
}: {
  text: string;
  user: { name: string; email: string; phone?: string };
  value: { min: number; max: number; area: number; avg: number };
  town: string;
  type: string;
  location: string;
}): TDocumentDefinitions => {
  const date = new Date();

  return {
    defaultStyle: {
      // fontSize: 8,
    },
    pageSize: 'A4',
    footer: {
      text: 'Generated by Eunit',
      alignment: 'right',
      margin: [10, 10],
    },
    content: [
      {
        alignment: 'left',
        columns: [
          logo,
          top,
          {
            marginLeft: 20,
            text: town,
            style: 'h1',
            color: '#141E49',
          },
        ],
      },
      {
        alignment: 'justify',
        columns: [
          {
            text: `Шалгуулагч`,
            style: 'h4',
          },
          {
            text: user.name,
            style: 'h4',
            color: '#7A808D',
          },
          { text: '' },
        ],
      },
      { text: '\n\n' },
      {
        columns: [
          {
            alignment: 'left',

            columnGap: 0,
            columns: [
              icons.result,
              {
                text: type,
                width: 80,
                marginLeft: 10,
                style: 'h4',
                alignment: 'left',
              },
              icons.time,
              {
                text: location,
                marginLeft: 10,
                style: 'h4',
                alignment: 'left',
              },
              {
                text: `${date.getFullYear()}.${date.getMonth() + 1}.${date.getDay()}\n\n`,
                style: 'h4',
                width: 60,
                marginLeft: 10,
                alignment: 'right',
              },
            ],
          },
        ],
      },
      { text: '\n\n' },
      {
        columns: [
          {
            text: 'Таны сонгосон орон сууцны м.кв-н үнэ цэн: ',
            style: 'h3',
          },
          {
            text: `${Formatter.money(`${value.min}`, 'MNT')}-${Formatter.money(`${value.max}`, 'MNT')}\n\n`,
            style: 'h3',
          },
        ],
      },
      { text: '\n\n' },
      {
        columns: [
          {
            text: 'Таны орон сууцны м.кв тохиромжит үнэ: ',
            style: 'h3',
          },
          {
            text: `${Formatter.money(`${value.avg}`, 'MNT')}\n\n`,
            style: 'h3',
            color: '#2850FA',
          },
        ],
      },
      { text: '\n\n' },
      {
        columns: [
          {
            text: `Таны ${value.area}м.кв орон сууцны нийт үнэ:`,
            style: 'h3',
            marginTop: 4,
          },
          {
            text: ` ${Formatter.money(
              `${Math.round(
                (Number(value.avg) || 0) *
                  (parseFloat(`${value.area}` || '0') || 0),
              )}`,
              'MNT',
            )} `,
            style: 'h3',
            background: '#2850FA',
            padding: 16,
            fontSize: 20,
            color: '#fff',
          },
        ],
      },
      { text: '\n\n' },
      {
        columns: [
          {
            text: `Овог нэр`,
            style: 'h4',
          },
          {
            text: user.name,
            style: 'h4',
            color: '#7A808D',
          },
          { text: '' },
        ],
      },
      {
        columns: [
          {
            text: `Цахим хаяг`,
            style: 'h4',
          },
          {
            text: user.email,
            style: 'h4',
            color: '#7A808D',
          },
          { text: '' },
        ],
      },
      {
        columns: [
          {
            text: `${user.phone && 'Утасны дугаар'}`,
            style: 'h4',
          },
          {
            text: user.phone ?? '',
            style: 'h4',
            color: '#7A808D',
          },
          { text: '' },
        ],
      },
      { text: '\n\n\n\n' },
      { text: text, fontSize: 9 },
      { text: '\n\n' },
      { text: 'Макро мэдээлэл', bold: true, fontSize: 20 },
      { text: '\n\n' },
      { text: 'Монгол банкны орон сууцны үнийн индекс', fontSize: 12 },
      {
        text: 'Орон сууцны борлуулалт болон түрээсийн үнийн чиг хандлага, сул орон тоо, хүн амын өсөлт хөгжил',
        fontSize: 9,
        color: '#7A808D',
      },
      { text: '\n\n' },
      {
        columnGap: 4,
        columns: [
          {
            columns: [
              {
                width: 180,
                columns: [
                  [
                    {
                      text: 'Сүүлийн 1 жилээр\n',
                      fontSize: 9,
                      color: '#7A808D',
                      margin: 0,
                    },
                    {
                      text: 'Орон сууцны үнийн өсөлт',
                      margin: 0,
                      fontSize: 12,
                    },
                  ],
                ],
              },
              {
                columns: [
                  icons[3],
                  {
                    text: `${oronSuutsniiUniinOsolt}%`,
                    fontSize: 16,
                    bold: true,
                  },
                ],
              },
            ],
          },
          {
            columns: [],
          },
        ],
      },
      { text: '\n' },
      {
        columnGap: 4,
        columns: [
          {
            columns: [
              {
                width: 180,
                columns: [
                  [
                    {
                      text: 'Сүүлийн 1 жилээр\n',
                      fontSize: 9,
                      color: '#7A808D',
                      margin: 0,
                    },
                    {
                      text: 'Хүн амын өсөлт хөгжил',
                      margin: 0,
                      fontSize: 12,
                    },
                  ],
                ],
              },
              {
                columns: [
                  icons[4],
                  {
                    text: `${hunAminOsoltHugjil}%`,
                    fontSize: 16,
                    bold: true,
                  },
                ],
              },
            ],
          },
          {
            columns: [
              {
                width: 180,
                columns: [
                  [
                    {
                      text: 'Сүүлийн 1 жилээр\n',
                      fontSize: 9,
                      color: '#7A808D',
                      margin: 0,
                    },
                    {
                      text: 'Хэрэглээний үнийн индекс',
                      margin: 0,
                      fontSize: 12,
                    },
                  ],
                ],
              },
              {
                columns: [
                  icons[5],
                  {
                    text: `${heregleeniiUniinIndex}%`,
                    fontSize: 16,
                    bold: true,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    styles: styles,
  };
};
